name: "CI"

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    branches:
      - "*"

permissions:
  contents: read

jobs:
  ci:
    uses: braintree/web-sdk-github-actions/.github/workflows/ci.yml@17a3922575160e8e3ffdb7ecc76c6a3dbfd6a50a
