name: "CI"

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    branches:
      - "*"

jobs:
  ci:
    uses: braintree/web-sdk-github-actions/.github/workflows/ci.yml@3d3621c5bb46edf879370cec4e63a34d345db4cf
